apiVersion: v1
kind: Service
metadata:
  name: board-service
  namespace: magicevents
spec:
  selector:
    app: board-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP