apiVersion: v1
kind: Service
metadata:
  name: gallery-service
  namespace: magicevents
spec:
  selector:
    app: gallery-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP