apiVersion: v1
kind: Service
metadata:
  name: guest-game-service
  namespace: magicevents
spec:
  selector:
    app: guest-game-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP