apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: magicevents
spec:
  selector:
    app: user-management-service
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP