apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s --namespace=magicevents
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: eventsetup-service
  name: eventsetup-service
  namespace: magicevents
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eventsetup-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s --namespace=magicevents
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: eventsetup-service
    spec:
      containers:
        - env:
            - name: SERVICES_BOARDSERVICE_URL
              value: https://board-service:8081
            - name: SERVICES_EVENTMANAGEMENT_URL
              value: https://events-management-service:8080
            - name: SERVICES_GALLERYSERVICE_URL
              value: https://gallery-service:8085
            - name: SERVICES_GUESTGAMESERVICE_URL
              value: https://guest-game-service:8083
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
          image: magicevents/eventsetup-service:latest
          imagePullPolicy: IfNotPresent
          name: eventsetup-service
          ports:
            - containerPort: 8086
              protocol: TCP
      restartPolicy: Always
