apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s --namespace=magicevents
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: events-management-db
  name: events-management-db
  namespace: magicevents
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: events-management-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s --namespace=magicevents
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: events-management-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: EventsManagementMEADB
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: user
          image: postgres:15
          name: events-management-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: events-management-data
            - mountPath: /docker-entrypoint-initdb.d
              name: events-management-db-cm1
      restartPolicy: Always
      volumes:
        - name: events-management-data
          persistentVolumeClaim:
            claimName: events-management-data
        - configMap:
            name: events-management-db-cm1
          name: events-management-db-cm1
