apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s --namespace=magicevents
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: frontend
    app: magicevents-frontend
  name: frontend
  namespace: magicevents
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: frontend
    app: magicevents-frontend
