apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s --namespace=magicevents
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: guest-game-service
  name: guest-game-service
  namespace: magicevents
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: guest-game-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s --namespace=magicevents
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: guest-game-service
    spec:
      containers:
        - env:
            - name: SERVICES_EVENTMANAGEMENT_URL
              value: http://events-management-service:8080
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://guest-game-db:5432/GuestGame
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
          image: magicevents/guest-game-service:latest
          imagePullPolicy: IfNotPresent
          name: guest-game-service
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
