apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s --namespace=magicevents
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-management-service
  name: user-management-service
  namespace: magicevents
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-management-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s --namespace=magicevents
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: user-management-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://user-management-db:5432/UserManagementMEADB
            - name: SPRING_DATASOURCE_USERNAME
              value: user
          image: magicevents/user-management-service:latest
          imagePullPolicy: IfNotPresent
          name: user-management-service
          ports:
            - containerPort: 8443
              protocol: TCP
      restartPolicy: Always
