apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-user-management-DB-pvc
  namespace: magicevents
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
