apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s --namespace=magicevents
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: guest-game-db
  name: guest-game-db
  namespace: magicevents
spec:
  ports:
    - name: "5434"
      port: 5434
      targetPort: 5432
  selector:
    io.kompose.service: guest-game-db
