apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: rabbitmq-data
  name: rabbitmq-data
  namespace: magicevents
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
