apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
  namespace: magicevents
  labels:
    app: user-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      containers:
        - name: user-management-service
          image: magicevents/user-management-service:latest
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8443
          env:
            - name: SERVER_PORT
              value: "8443"